"""Bake the glyphs of the reset countdown ("2시간 5분", "2h 5m", "2h 5min", "4j 3h", "2時間5分", "2小时5分") into a
1-bit C header for the SmallTV firmware.

The built-in TFT_eSPI fonts have no CJK and a full font would not fit, so only digits, space
and the unit words of the supported languages are rendered. Pixel fonts at their native size
(no anti-aliasing) stay crisp under the 1px outline the firmware adds.

  Galmuri14 15px - digits, space, Korean units, Latin units of en/es/pt/fr/de/it (chosen by the user
                   as most readable)
  Unifont 16px   - Japanese, Chinese, Cyrillic (ru/uk) and Thai units: Galmuri has none of simplified
                   时, Cyrillic or Thai; one font for all CJK keeps the shared 分 consistent.
  Arabic: Unifont's Arabic is too small to read at this size, so the device uses English units.

    .venv/bin/python tools/gen_glyphs.py [--preview out.png]

Fonts live in tools/fonts with their SIL OFL licenses.
"""
import argparse
import math
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parent.parent
FONTS = ROOT / "tools" / "fonts"
OUT = ROOT / "firmware" / "usagebar" / "src" / "glyphs.h"
HEIGHT = 16  # glyph box height; the firmware centres it in the 22px bar

SETS = [  # (font file, native pixel size, characters)
    ("Galmuri14.ttf", 15, "0123456789 .일시간분dhminjTgozusakp"),
    ("unifont.otf", 16, "日時間分天小时дчмингохвวชมน"),
]
SAMPLES = ["2시간 5분", "2h 5m", "2h 5min", "4j 3h", "4T 3h", "4g 3h", "2godz 5min", "2u 5min", "2sa 5dk",
           "4ng 3h", "2j 5m", "2時間5分", "2小时5分", "2小時5分", "2ч 5мин", "2год 5хв", "2ชม. 5น."]


def render(ch, font):
    """One glyph on the font's baseline, as wide as its advance."""
    ascent, descent = font.getmetrics()
    width = max(1, math.ceil(font.getlength(ch)))
    img = Image.new("1", (width, HEIGHT), 0)
    draw = ImageDraw.Draw(img)
    draw.fontmode = "1"  # no anti-aliasing: pixel fonts at native size are exact
    draw.text((0, (HEIGHT - (ascent + descent)) // 2), ch, font=font, fill=1)
    return img


def pack(img):
    w, h = img.size
    stride = (w + 7) // 8
    data = bytearray(stride * h)
    px = img.load()
    for y in range(h):
        for x in range(w):
            if px[x, y]:
                data[y * stride + x // 8] |= 0x80 >> (x % 8)
    return bytes(data)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--preview", help="write an enlarged preview PNG of every language")
    args = ap.parse_args()

    glyphs = {}
    for font_file, size, chars in SETS:
        font = ImageFont.truetype(str(FONTS / font_file), size)
        for ch in chars:
            if ch in glyphs:
                raise SystemExit(f"{ch!r} is in two glyph sets")
            glyphs[ch] = render(ch, font)

    lines = [
        "// Generated by tools/gen_glyphs.py - do not edit.",
        "// " + "; ".join(f"{f} {s}px" for f, s, _ in SETS) + " (SIL OFL 1.1).",
        "// 1-bit, MSB first, rows padded to whole bytes.",
        "#pragma once",
        "#include <pgmspace.h>",
        "",
        "struct Glyph {",
        "  uint16_t codepoint;",
        "  uint8_t width;  // advance width in pixels",
        "  const uint8_t *bits;",
        "};",
        "",
        f"static const uint8_t GLYPH_HEIGHT = {HEIGHT};",
        "",
    ]
    for i, (ch, img) in enumerate(glyphs.items()):
        lines.append(f"static const uint8_t GLYPH_{i}[] PROGMEM = {{{', '.join(f'0x{b:02X}' for b in pack(img))}}};  // '{ch}'")
    lines += ["", "static const Glyph GLYPHS[] = {"]
    lines += [f"    {{0x{ord(ch):04X}, {img.size[0]}, GLYPH_{i}}},  // '{ch}'" for i, (ch, img) in enumerate(glyphs.items())]
    lines += ["};", f"static const uint8_t GLYPH_COUNT = {len(glyphs)};", ""]
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT.relative_to(ROOT)}: {len(glyphs)} glyphs, {sum(len(pack(g)) for g in glyphs.values())} bytes")

    if args.preview:
        rows = []
        for text in SAMPLES:
            w = sum(glyphs[c].size[0] for c in text)
            line = Image.new("1", (w, HEIGHT), 0)
            x = 0
            for c in text:
                line.paste(glyphs[c], (x, 0))
                x += glyphs[c].size[0]
            rows.append(line)
        sheet = Image.new("1", (max(r.size[0] for r in rows) + 8, (HEIGHT + 4) * len(rows)), 0)
        for i, r in enumerate(rows):
            sheet.paste(r, (4, i * (HEIGHT + 4) + 2))
        sheet.convert("L").resize((sheet.size[0] * 5, sheet.size[1] * 5), Image.NEAREST).save(args.preview)
        print("preview", args.preview)


if __name__ == "__main__":
    main()
