"""Build the SmallTV usage screen's pixel art: animated service icons and weather icons.

Service icons are stored as a few sprites (poses) plus a timeline of tiny steps
"draw sprite S at (x, y), maybe mirrored, maybe with another layer on top". The device
composes each 40x22 frame on the fly and, after each behaviour (sequence), picks the next one
at random. That gives hundreds of frames for a few KB.

  claude, codex - poses + behaviour sequences designed by the Codex CLI (tools/icons/mascots.json);
                  Clawd was seeded from the Claude Code welcome banner's block characters
  antigravity   - the Gemini sparkle, poses + sequences by the Codex CLI (tools/icons/gemini.json)
Weather icons: 28x28, drawn by the Codex CLI (tools/icons/weather.json).

Writes firmware/usagebar/src/icons.h. Pixels are 4-bit palette indices (0 = transparent).

    .venv/bin/python tools/gen_icons.py [--preview out.gif]
"""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ICONS_DIR = ROOT / "tools" / "icons"
OUT = ROOT / "firmware" / "usagebar" / "src" / "icons.h"
CELL_W, CELL_H = 40, 22
WX_SIZE = 28
FLIP, LAYER = 1, 2  # step flags: mirror the sprite / another layer follows in the same frame


class Anim:
    def __init__(self, fps, palette):
        self.fps, self.palette = fps, palette
        self.sprites, self.names = [], {}
        self.sequences = []  # list of frames; a frame is a list of (sprite, x, y, flip)

    def sprite(self, name, rows):
        self.names[name] = len(self.sprites)
        self.sprites.append(rows)

    def seq(self, frames):
        self.sequences.append([[(self.names[n], x, y, f) for n, x, y, f in fr] for fr in frames])


def mirror(rows):
    return [r[::-1] for r in rows]


# ---------- animations designed by the Codex CLI ----------

def build_from_codex(src, fps=10):
    """Poses + sequences from tools/icons/mascots.json."""
    a = Anim(fps, src["palette"])
    for name, rows in src["poses"].items():
        a.sprite(name, rows)
    for seq in src["sequences"]:
        a.seq([[(l["pose"], int(l["x"]), int(l["y"]), FLIP if l.get("flip") else 0) for l in frame]
               for frame in seq["frames"]])
    return a


# ---------- encoding ----------

def rgb565(hexcolor):
    r, g, b = (int(hexcolor[i:i + 2], 16) for i in (1, 3, 5))
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def pack(rows, index):
    nibbles = [index.get(c, 0) for r in rows for c in r]
    if len(nibbles) % 2:
        nibbles.append(0)
    return bytes((nibbles[i] << 4) | nibbles[i + 1] for i in range(0, len(nibbles), 2))


def palette_of(spec):
    keys = list(spec)
    if len(keys) > 15:
        raise SystemExit("too many colours")
    pal = [0] + [rgb565(spec[k]) for k in keys]
    return {k: i + 1 for i, k in enumerate(keys)}, pal + [0] * (16 - len(pal))


def hexbytes(data):
    return ", ".join(f"0x{b:02X}" for b in data)


def render(anim, frame):
    """Compose one frame -> 40x22 grid of palette keys (for the preview)."""
    cell = [["."] * CELL_W for _ in range(CELL_H)]
    for s, x, y, flip in frame:
        rows = anim.sprites[s]
        rows = mirror(rows) if flip else rows
        for r, row in enumerate(rows):
            for c, ch in enumerate(row):
                if ch in anim.palette and 0 <= y + r < CELL_H and 0 <= x + c < CELL_W:
                    cell[y + r][x + c] = ch
    return cell


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--preview", help="write an enlarged animated GIF preview (every sequence in order)")
    args = ap.parse_args()

    mascots = json.loads((ICONS_DIR / "mascots.json").read_text())
    gemini = json.loads((ICONS_DIR / "gemini.json").read_text())
    anims = {"claude": build_from_codex(mascots["claude"]), "codex": build_from_codex(mascots["codex"]),
             "antigravity": build_from_codex(gemini, fps=8)}
    weather = json.loads((ICONS_DIR / "weather.json").read_text())

    lines = [
        "// Generated by tools/gen_icons.py - do not edit.",
        "// Sprites: 4-bit palette indices, two pixels per byte (high nibble first), 0 = transparent.",
        "#pragma once",
        "#include <pgmspace.h>",
        "",
        f"static const uint8_t ICON_W = {CELL_W}, ICON_H = {CELL_H};",
        f"static const uint8_t WX_SIZE = {WX_SIZE};",
        f"static const uint8_t STEP_FLIP = {FLIP}, STEP_LAYER = {LAYER};",
        "",
        "struct IconSprite { uint8_t w, h; uint16_t offset; };  // offset into pixels[]",
        "struct IconStep { uint8_t sprite; int8_t x, y; uint8_t flags; };",
        "",
        "struct IconAnim {",
        "  const char *id;  // provider id",
        "  uint8_t fps;",
        "  uint16_t palette[16];",
        "  const IconSprite *sprites;  // PROGMEM",
        "  const uint8_t *pixels;      // PROGMEM",
        "  const IconStep *steps;      // PROGMEM",
        "  const uint16_t *seqStart;   // PROGMEM, seqCount + 1 entries (step index of each sequence)",
        "  uint8_t seqCount;",
        "};",
        "",
        "struct WeatherIcon {",
        "  const char *name;",
        "  uint16_t palette[16];",
        "  const uint8_t *data;  // WX_SIZE * WX_SIZE / 2 bytes",
        "};",
        "",
    ]
    entries, total_frames, total_bytes = [], 0, 0
    for pid, a in anims.items():
        P = pid.upper()
        index, pal = palette_of(a.palette)
        pixels, table = b"", []
        for rows in a.sprites:
            table.append(f"{{{len(rows[0])}, {len(rows)}, {len(pixels)}}}")
            pixels += pack(rows, index)
        steps, starts = [], []
        for seq in a.sequences:
            starts.append(len(steps))
            for frame in seq:
                for k, (s, x, y, flip) in enumerate(frame):
                    flags = (FLIP if flip else 0) | (LAYER if k < len(frame) - 1 else 0)
                    steps.append(f"{{{s}, {x}, {y}, {flags}}}")
            total_frames += len(seq)
        starts.append(len(steps))
        total_bytes += len(pixels) + 4 * len(steps)
        lines += [
            f"static const IconSprite SPR_{P}[] PROGMEM = {{{', '.join(table)}}};",
            f"static const uint8_t PIX_{P}[] PROGMEM = {{{hexbytes(pixels)}}};",
            f"static const IconStep STEP_{P}[] PROGMEM = {{{', '.join(steps)}}};",
            f"static const uint16_t SEQ_{P}[] PROGMEM = {{{', '.join(map(str, starts))}}};",
            "",
        ]
        entries.append(f'    {{"{pid}", {a.fps}, {{{", ".join(f"0x{c:04X}" for c in pal)}}}, '
                       f"SPR_{P}, PIX_{P}, STEP_{P}, SEQ_{P}, {len(a.sequences)}}},")
    lines += ["static const IconAnim ICON_ANIMS[] = {", *entries, "};",
              f"static const uint8_t ICON_ANIM_COUNT = {len(entries)};", ""]

    wx_entries = []
    for name, icon in weather.items():
        index, pal = palette_of(icon["palette"])
        lines.append(f"static const uint8_t WX_{name.upper()}[] PROGMEM = {{{hexbytes(pack(icon['rows'], index))}}};")
        wx_entries.append(f'    {{"{name}", {{{", ".join(f"0x{c:04X}" for c in pal)}}}, WX_{name.upper()}}},')
    lines += ["", "static const WeatherIcon WEATHER_ICONS[] = {", *wx_entries, "};",
              f"static const uint8_t WEATHER_ICON_COUNT = {len(wx_entries)};", ""]
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT.relative_to(ROOT)}: " + ", ".join(
        f"{p} {len(a.sprites)} sprites/{len(a.sequences)} seqs/{sum(len(s) for s in a.sequences)} frames"
        for p, a in anims.items()) + f"; animation data {total_bytes} bytes for {total_frames} frames")

    if args.preview:
        from PIL import Image

        scale, gap = 5, 6
        timelines = [[fr for seq in a.sequences for fr in seq] for a in anims.values()]
        frames = []
        for t in range(max(len(tl) for tl in timelines)):
            img = Image.new("RGB", ((CELL_W + gap) * scale * len(anims), CELL_H * scale), (0, 0, 0))
            for k, (a, tl) in enumerate(zip(anims.values(), timelines)):
                for y, row in enumerate(render(a, tl[t % len(tl)])):
                    for x, c in enumerate(row):
                        if c in a.palette:  # anything else (".", " ") is transparent
                            col = tuple(int(a.palette[c][i:i + 2], 16) for i in (1, 3, 5))
                            x0 = (k * (CELL_W + gap) + x) * scale
                            img.paste(col, (x0, y * scale, x0 + scale, (y + 1) * scale))
            frames.append(img)
        frames[0].save(args.preview, save_all=True, append_images=frames[1:], duration=110, loop=0)
        print("preview", args.preview, len(frames), "frames")


if __name__ == "__main__":
    main()
